"""Water-surface mask for SAR detections.

The CFAR vessel detector produces hits anywhere it sees high backscatter:
real ships, bridges, port cranes, oil platforms, buildings near coasts,
and — disproportionately — terrain features and inland infrastructure.
Without a water-surface filter, the AoI agent clusters land-based false
positives as if they were ships, producing demo-killing oddities like
"Western Achaia Field — 8 vessels" over Peloponnese farmland (see
[`docs/AOI_QUALITY_REPORT.md`](../docs/AOI_QUALITY_REPORT.md) §3).

This module loads every sea/EEZ polygon in `data/geojson/`, unions them
into a single multipolygon, and exposes:

    is_over_water(lat, lon, coastal_buffer_deg=0.0) -> bool
    flag_rows(rows) -> Iterable of (row, is_water_bool)

The union is buffered slightly on first use (default 0.0 — strict water
only; pass a small positive buffer to include estuaries and harbors).
Lookups go through a prepared geometry so per-point cost is O(log n) over
polygon vertices.

The module degrades gracefully: if the GeoJSON files are missing or
shapely is not installed, ``is_over_water`` returns ``True`` for everything
(safe-default — don't drop data when we can't classify). A warning is
logged once at first use.
"""
from __future__ import annotations

import json
import logging
from functools import lru_cache
from pathlib import Path
from typing import Iterable

log = logging.getLogger(__name__)

# Files to union. Order doesn't matter — we always union them all.
# greek_eez covers the bulk; aegean / ionian / eastern_med add the
# neighbour-region waters where Greek-relevant clusters cross sovereignty.
# `_water_surface.geojson` is the precise mask (sea bbox MINUS Greek land,
# generated by `scripts/build_water_mask.py`). When present, we use it
# exclusively. The bbox-rectangle fallbacks below are kept for legacy use
# (they classify Phthiotis mountains as water, so they're worse — but
# better than nothing if the generator hasn't run).
WATER_GEOJSONS = (
    "_water_surface.geojson",
)
WATER_GEOJSON_FALLBACKS = (
    "greek_eez.geojson",
    "aegean_sea.geojson",
    "ionian_sea.geojson",
    "eastern_med.geojson",
)

# Resolve the geojson directory relative to this file so the helper works
# regardless of CWD (tests / scripts / uvicorn).
_GEOJSON_DIR = Path(__file__).resolve().parents[2] / "data" / "geojson"


@lru_cache(maxsize=1)
def _water_geom():
    """Return a single shapely (Multi)Polygon for all water surfaces.

    Cached after first call. Returns None if anything goes wrong (missing
    geojsons, shapely unavailable, parse error) so callers fall back to
    "everything is water" rather than dropping legitimate data.
    """
    try:
        from shapely.geometry import shape
        from shapely.ops import unary_union
    except ImportError:
        log.warning("shapely not available — water mask disabled, treating all detections as water")
        return None

    geoms = []
    # Try the precise mask first; fall back to bbox rectangles only if it's missing.
    primary_loaded = False
    candidates = list(WATER_GEOJSONS)
    for name in candidates:
        path = _GEOJSON_DIR / name
        if path.exists():
            primary_loaded = True
            break
    if not primary_loaded:
        log.warning("water mask: %s not found; falling back to bbox rectangles "
                    "(run scripts/build_water_mask.py to generate the precise mask)",
                    WATER_GEOJSONS[0])
        candidates = list(WATER_GEOJSON_FALLBACKS)

    for name in candidates:
        path = _GEOJSON_DIR / name
        if not path.exists():
            log.warning("water mask: %s missing — skipping", name)
            continue
        try:
            doc = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            log.warning("water mask: %s unreadable (%s) — skipping", name, exc)
            continue
        # Either a single Feature/Geometry or a FeatureCollection
        if doc.get("type") == "FeatureCollection":
            for feat in doc.get("features", []):
                g = feat.get("geometry")
                if g: geoms.append(shape(g))
        elif "geometry" in doc:
            geoms.append(shape(doc["geometry"]))
        elif "type" in doc:
            geoms.append(shape(doc))

    if not geoms:
        log.warning("water mask: no usable geometries — disabling filter")
        return None

    try:
        union = unary_union(geoms)
        # Pre-fix any minor self-intersection so contains() doesn't choke.
        if not union.is_valid:
            union = union.buffer(0)
        return union
    except Exception as exc:
        log.warning("water mask: union failed (%s) — disabling filter", exc)
        return None


def is_over_water(lat: float | None, lon: float | None,
                  coastal_buffer_deg: float = 0.0) -> bool:
    """Return True iff (lat, lon) is over a sea/EEZ surface.

    A small ``coastal_buffer_deg`` (e.g. 0.01 ≈ 1 km) can be passed to
    treat near-coast detections as water — useful for tolerating GPS noise
    in real AIS broadcasts that put the ship a few hundred metres inland.

    Safe-default: returns True when the mask is unavailable or coordinates
    are missing — we never silently drop data on infrastructure failure.
    """
    if lat is None or lon is None:
        return True
    geom = _water_geom()
    if geom is None:
        return True
    try:
        from shapely.geometry import Point
    except ImportError:
        return True
    pt = Point(lon, lat)
    if coastal_buffer_deg > 0:
        pt = pt.buffer(coastal_buffer_deg)
    try:
        return bool(geom.contains(pt) if coastal_buffer_deg == 0 else geom.intersects(pt))
    except Exception:
        return True


def flag_rows(rows: Iterable[tuple[float | None, float | None]],
              coastal_buffer_deg: float = 0.0) -> list[bool]:
    """Batch helper: returns a parallel list of bool flags for each (lat, lon)."""
    return [is_over_water(lat, lon, coastal_buffer_deg) for lat, lon in rows]


def diagnostics() -> dict[str, object]:
    """One-shot health probe — used by the backfill script to confirm the
    mask is doing something before it touches the fact store."""
    geom = _water_geom()
    if geom is None:
        return {"status": "disabled", "reason": "no usable geometries / shapely missing"}
    # Quick sanity check: known-water and known-land points
    SEA_POINT  = (37.5, 25.5)   # central Aegean
    LAND_POINT = (38.6, 22.7)   # Phthiotis (the AoI report's false-positive zone)
    return {
        "status":           "enabled",
        "files_attempted":  list(WATER_GEOJSONS),
        "aegean_passes":    is_over_water(*SEA_POINT),
        "phthiotis_blocks": not is_over_water(*LAND_POINT),
        "bounds":           tuple(round(b, 3) for b in geom.bounds),
    }
